[package]
name = "ping-tokio"
version = "0.5.0"
edition = "2021"
authors = [
    "Bob McWhirter <bmcwhirt@redhat.com>",
    "Ulf Lilleengen <lulf@redhat.com>"
]

[dependencies]
embedded-tls = { path = "../..", features = ["log", "tokio"] }
embassy-crypto-rand = { git = "https://github.com/embassy-rs/embassy", rev = "822a76ea91f2c0885c6eb0c65fe91181e31133e1" }
embassy-crypto-rustcrypto = { git = "https://github.com/embassy-rs/embassy", rev = "822a76ea91f2c0885c6eb0c65fe91181e31133e1", features = ["embassy-crypto-sha256", "embassy-crypto-hmac-sha256", "embassy-crypto-aes128-gcm", "embassy-crypto-p256-ecdh", "embassy-crypto-p256-ecdsa"] }
embedded-io-adapters = { version = "0.7", features = ["tokio-1"] }
embedded-io-async = "0.7"
env_logger = "0.10"
tokio = { version = "1", features = ["full"] }
log = "0.4"
pem-parser = "0.1.1"
